# Generated by Django 4.2.7 on 2023-11-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerinvoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
