# Generated by Django 4.2.7 on 2023-11-26 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customerinvoices", "0003_alter_invoice_amount_alter_receipt_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="customerinvoices.customer",
            ),
        ),
    ]
