# Generated by Django 4.2.7 on 2023-11-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerinvoices", "0004_alter_receipt_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
