# Generated by Django 4.2.7 on 2023-11-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerinvoices", "0005_alter_invoice_amount_alter_receipt_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="discount_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="discount_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
