# Generated by Django 4.2.7 on 2023-11-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerinvoices", "0006_alter_invoice_discount_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="UnPaid",
                max_length=50,
            ),
        ),
    ]
