# Generated by Django 4.2.7 on 2023-11-27 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customerinvoices", "0007_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="brand_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="brand_name",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=150, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
