# Generated by Django 4.2.7 on 2023-11-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customerinvoices", "0008_invoice_brand_name_receipt_brand_name_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="brand_name",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="brand_name",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
